### ISSUE TITLE
works nice on win10, but unusable on ubuntu (too noizzy)

### ISSUE THREAD

**Issue by elpimous** [Fuhua-Chen/ReSpeaker_Microphone_Array_Firmware#9]
Hello,
The recording on windows 10 is perfect.
But, on ubuntu, I can't use it (and I bought it for ubuntu usage !!)
my voice is lost in the noizzy sounds.

tested on a desktop and a laptop.

on the laptop, win10 ok.

            on the same laptop, just after ubuntu 16.04 fresh install,
            I run the rules, to avoid sudo,
            installed pyaudio and respeaker --update,

connect the respeaker mic array to usb port, and try a sox mono 16000 : very very poor record !!
one example : http://dl.free.fr/dsRBiRGZC

Strange : sometimes, record is clear (unstable !!)

I tested 2 differents usb cables,
tested with 2 last firmwares raw and xvsm,
board fixed on a plastic mount, never touched by fingers.

Physical mics must work, as it works nicely on win10.

Is it a ubuntu driver or anything ?

Please help, I can't do anything for now

Best regards, Vincent

**Comment by elpimous** [comment]
on the ubuntu sound parameters, I can see :
internal microphone
numeric entry S/PDIF (respeaker)
microphone (respeaker)

I tested with each of respeaker inputs, both, but bad records !!

**Comment by Fuhua-Chen** [comment]
please try to record using audacity first. it will show you if it is work normally or not

**Comment by elpimous** [comment]
Solved. Thanks
